export const ROOT_CATEGORY_LIST_REQUEST = "ROOT_CATEGORY_LIST_REQUEST";
export const ROOT_CATEGORY_LIST_SUCCESS = "ROOT_CATEGORY_LIST_SUCCESS";
export const ROOT_CATEGORY_LIST_FAIL = "ROOT_CATEGORY_LIST_FAIL";

export const ROOT_CATEGORY_LIST_BY_ID_REQUEST =
  "ROOT_CATEGORY_LIST_BY_ID_REQUEST";
export const ROOT_CATEGORY_LIST_BY_ID_SUCCESS =
  "ROOT_CATEGORY_LIST_BY_ID_SUCCESS";
export const ROOT_CATEGORY_LIST_BY_ID_FAIL = "ROOT_CATEGORY_LIST_BY_ID_FAIL";

export const ROOT_CATEGORY_DELETE_REQUEST = "ROOT_CATEGORY_DELETE_REQUEST";
export const ROOT_CATEGORY_DELETE_SUCCESS = "ROOT_CATEGORY_DELETE_SUCCESS";
export const ROOT_CATEGORY_DELETE_FAIL = "ROOT_CATEGORY_DELETE_FAIL";

export const ROOT_CATEGORY_CREATE_REQUEST = "ROOT_CATEGORY_CREATE_REQUEST";
export const ROOT_CATEGORY_CREATE_SUCCESS = "ROOT_CATEGORY_CREATE_SUCCESS";
export const ROOT_CATEGORY_CREATE_FAIL = "ROOT_CATEGORY_CREATE_FAIL";
export const ROOT_CATEGORY_CREATE_RESET = "ROOT_CATEGORY_CREATE_RESET";

export const ROOT_CATEGORY_UPDATE_REQUEST = "ROOT_CATEGORY_UPDATE_REQUEST";
export const ROOT_CATEGORY_UPDATE_SUCCESS = "ROOT_CATEGORY_UPDATE_SUCCESS";
export const ROOT_CATEGORY_UPDATE_FAIL = "ROOT_CATEGORY_UPDATE_FAIL";
export const ROOT_CATEGORY_UPDATE_RESET = "ROOT_CATEGORY_UPDATE_RESET";
